<<<<<<< Updated upstream
# Generated by Django 3.2.9 on 2021-11-24 23:34
=======
# Generated by Django 2.1.3 on 2021-11-23 14:34
>>>>>>> Stashed changes

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='urldb',
            fields=[
<<<<<<< Updated upstream
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lurl', models.TextField(max_length=200)),
                ('surl', models.TextField(max_length=3)),
=======
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.TextField(max_length=200)),
                ('short_url', models.TextField(max_length=3)),
>>>>>>> Stashed changes
            ],
        ),
    ]
