# Generated by Django 3.2.9 on 2021-11-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='url_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.TextField(max_length=200)),
                ('short_url', models.TextField(max_length=3)),
            ],
        ),
    ]
